# Generated by Django 4.1.13 on 2025-10-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_sales_bill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
