# Generated by Django 4.1.13 on 2025-10-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_remove_item_discount_sales_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1),
        ),
        migrations.AlterField(
            model_name='sales',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1),
        ),
    ]
