# Generated by Django 4.1.13 on 2025-10-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_item_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
