# Generated by Django 4.1.13 on 2025-10-25 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_item_stock_alter_item_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='stock',
        ),
    ]
