# Generated by Django 4.1.13 on 2025-10-27 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
