# Generated by Django 4.1.13 on 2025-10-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_userprofile_can_add_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='can_add_sale',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_delete_sale',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_edit_sale',
            field=models.BooleanField(default=True),
        ),
    ]
