# Generated by Django 4.1.13 on 2025-10-27 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_remove_sales_item_remove_sales_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.userprofile'),
        ),
    ]
