# Generated by Django 3.2 on 2025-10-29 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0037_saleitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='item',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='rate',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sales',
            name='bill_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sales',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
