# Generated by Django 4.2.16 on 2025-10-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='bill_number',
            field=models.CharField(max_length=50),
        ),
    ]
