# Generated by Django 4.1.13 on 2025-10-22 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_item_stock_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='stock_quantity',
            new_name='quantity',
        ),
    ]
