# Generated by Django 4.1.13 on 2025-10-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_category_created_at_category_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_by',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_by',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='sales',
            name='created_by',
            field=models.CharField(default='Admin', max_length=100),
        ),
    ]
