# Generated by Django 4.1.13 on 2025-10-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_category_created_by_alter_item_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], default='Cash', max_length=10),
        ),
        migrations.AlterField(
            model_name='sales',
            name='created_by',
            field=models.CharField(default='Admin', max_length=100),
        ),
    ]
