# Generated by Django 4.1.13 on 2025-10-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_sales_payment_mode_alter_sales_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sales',
            name='status',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
