# Generated by Django 4.1.13 on 2025-10-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_remove_item_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('viewer', 'Viewer')], default='viewer', max_length=10),
        ),
    ]
