# Generated by Django 4.1.13 on 2025-10-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_alter_userprofile_can_add_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='can_add_category',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_add_item',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_delete_category',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_delete_item',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_edit_category',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_edit_item',
            field=models.BooleanField(default=True),
        ),
    ]
