# Generated by Django 4.1.13 on 2025-10-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_alter_userprofile_can_add_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_access_category_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_access_item_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_access_sales_page',
            field=models.BooleanField(default=True),
        ),
    ]
