# Generated by Django 4.1.13 on 2025-10-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_userprofile_can_access_category_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_customized_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
