# Generated by Django 4.1.13 on 2025-10-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0032_alter_sales_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='bill_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
