# Generated by Django 3.2 on 2025-10-29 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0033_alter_sales_bill_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_customized_by_admin',
        ),
        migrations.AddField(
            model_name='sales',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sales',
            name='bill_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sales',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.DeleteModel(
            name='SalesItem',
        ),
    ]
