# Generated by Django 3.2 on 2025-10-29 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_auto_20251029_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_customized_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sales',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.item'),
        ),
    ]
